apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse-serving
  labels:
    app.kubernetes.io/part-of: lakehouse-platform
    platform.bank/owner: data-platform
    platform.bank/environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
