apiVersion: v1
kind: ServiceAccount
metadata:
  name: trino
  namespace: lakehouse-serving
  labels:
    app.kubernetes.io/name: trino
    platform.bank/owner: data-platform
    platform.bank/environment: production
automountServiceAccountToken: false
