apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-job-manager
  namespace: lakehouse-processing
rules:
  - apiGroups: [sparkoperator.k8s.io]
    resources: [sparkapplications]
    verbs: [create, get, list, watch, delete]
